### ISSUE TITLE
Signature Switch doesn't work with new Thunderbird

### ISSUE THREAD

**Issue by teknowledgist** [4ch1m/mozext#1]
Hi.  Thank you, thank you for Signature Switch.  It has been my most valued add-on to Thunderbird since close to (if not) when you released it 15 years ago.  

Unfortunately, it's not working with the new Thunderbird (78.1.0).  Is there a chance that it can be made to work, or will it be going the way of the dodo like so many of the great FireFox add-ons that were doomed with the change to "Quantum"?  (almost 3 years, and I still miss them 😢 )

**Comment by jobisoft** [comment]
Hi Achim,

Thunderbird has created a new staff position called "Add-on support engineer" - which happens to be me (John Bieling). In the last weeks I have worked on a shortcut update path, to get legacy extensions working in TB78 again, with the minimal amount of work possible. It is using an Experiment wrapper API:
https://github.com/thundernest/addon-developer-support/wiki

After the initial update, we can remove the legacy parts step by step. The idea is to get add-on compatible as easy and as fast as possible and do the "full" conversion to a true MailExtension without Experiment APIs in smaller steps, while your users can already use your add-on in TB78.

I would love to see your add-on in TB78 and I offer help via our community channels:
https://developer.thunderbird.net/add-ons/community

**Comment by tvercaut** [comment]
I am missing this add-on as well (among others) since being upgraded to TB78. Is there a useable alternative out there? Searching for "signature" within the TB78 compatible add-ons didn't produce much helpful results.

**Comment by tvercaut** [comment]
For the record, I found out that [Quicktext](https://github.com/jobisoft/quicktext) by @jobisoft is a good enough alternative for my needs. I initially thought it didn't work wither with TB78 but then saw [this comment](https://addons.thunderbird.net/en-US/thunderbird/addon/quicktext/reviews/1163145/) and realised that configuration was simply not where I expected to find it (i.e. you have to go through the tools - addon options menu).

**Comment by 4ch1m** [comment]
Hi there,
sorry for jumping in to the discusson so late.
As you may already have seen: I've decided not to put any more time and effort in working with the legacy-codebase (XUL/XPCOM) of SignatureSwitch.
I already started to build the addon from scratch; as a pure WebExtension/MailExtension (see: [Signature Switch ME](https://github.com/4ch1m/mozext/tree/master/signatureswitch-me)).
I hope it will be "ready for production" soon. Stay tuned! :smiley:
