### ISSUE TITLE
Links unclickables

### ISSUE THREAD

**Issue by AtomikRemy** [4ch1m/mozext#100]
Hi,
Since the last update of Signature Switch (great extension !), I can't open the boxes TXT or HTML. 
The link seems to be here (with the little hand) but nothing works : I can't close the "Aa Text" bos or open the </> HTML...
I'm using Thunderbird Supernova 115.7.0 on W11.
Any help pls ?

**Comment by 4ch1m** [comment]
Hey there,

that is a bug that (unfortunately) got introduced with the new/updated version of SignatureSwitch (2.16.3).
I updated an underlying framework/library (mdb-ui-kit); which is now causing this problem.

I'll try to provide a fix (and a new release -> 2.17.0) as time permits.

Thank you very much for bringing this to my attention!

**Comment by AtomikRemy** [comment]
Thanks to you for your so quick answer !

**Comment by 4ch1m** [comment]
This will fix the issue: 2addc026fd4151bac35c061a05a8a754ef20ee65

The new version (`2.17.0`) should be available at [addons.thunderbird.net](https://addons.thunderbird.net) soon.

**Comment by AtomikRemy** [comment]
Great ! Thks again.
