### ISSUE TITLE
[Feature] Allow inserting signature under current message, but below previous message dialog

### ISSUE THREAD

**Issue by typoworx-de** [4ch1m/mozext#101]
Currently using button "Signature Switch", the signature will be appended below all messages if using in a message conversation one wants to insert the signature again below the own answer and before the previous communication.

I've been switching to signature-switch in hope I'm able to disable automatic signature. In some message/conversions it's annoying to always have repeating signatures. So in some dialogs it's fine to only have manual greetings without signature. But for some customers/dialogs it would be a good option to insert the signature manually (f.e. forwarding a message/dialog or if there is someone new joining the e-mail dialog).

Is it possible to insert the Signature in "right place" and not automatically below all messages/dialog?

Example:

```
My answer .....

greetings

<--- INSERTED SIGNATURE SHOULD GO HERE!

On 23.04.24 14:21, someone wrote:

Blablabla

Acme Company
Sales Team

On 23.04.24 14:21,  someone else wrote:

Yes shure.

Acme Company
Support Team

MY-INSERTED-SIGNATURE
```

Actually Thunderbird itself has such options already for the internal signature feature:
![image](https://github.com/4ch1m/mozext/assets/1282298/489161a0-efd2-4f16-8000-9f6657546ab0)

Is it possible to adopt this for signature-switch extension?
Or if not trivial maybe we could use some kind of "placeholder" or (invisible) HTML-TAG in the thunderbird internal signature to track the correct position for inserting the signature using Insert-Signature?

**Comment by 4ch1m** [comment]
There already is an option for this in Signature Switch; however it is not recommended to use.
Check the "Miscellaneous"-tab in the settings dialog.
