### ISSUE TITLE
Automatic switch for html / plain text

### ISSUE THREAD

**Issue by fulljackz** [4ch1m/mozext#11]
Hi
Thanks for your great extension. I juste created two signature : html and text.

Is there a way to configure an auto switch between them if I use text and html email composing ?

Thanks !

**Comment by 4ch1m** [comment]
You already can fill both the text- and html-section in ONE signature-item within the options.
The appropriate one will be chosen depending on which mode you are composing in.
Also... if you compose in HTML-mode bu thave not entered a html-portion in the signature, it will fallback to the plaintext-part.
(However, the fallback only works this way... plaintext -> html... not: html -> plaintext.)
