### ISSUE TITLE
Unabled to create signature

### ISSUE THREAD

**Issue by Bishop-Berkley** [4ch1m/mozext#12]
Running Windows 10 Thunderbird 78.3.3.  Had to reinstall SW in order to get the menu to appear.  It does not recognise any previous signature files, even though they are still in the C:\Users\*********\AppData\Roaming\Thunderbird\Profiles\*********.default\Signatures directory.  So, I chose SW button>Signatures>New Signature  I can change the name, but I can't edit the default text (plain or html).  The "Moe Zilla" text is not selectable.  The cursor sits in the upper left corner of the edit window.  Suggestions?  Thanks.

--------- UPDATE --------- 
I changed the name of the signature and saved it.  Opened a new message, Inserted the signature, which was empty.  From the message window I selected SW button>Options and then I was able to edit the signature.  In other words, it fixed itself.  But there is a bug in there somewhere.  Hope that helps.

**Comment by 4ch1m** [comment]
> Running Windows 10 Thunderbird 78.3.3. Had to reinstall SW in order to get the menu to appear.

In case you haven't noticed.
Thunderbird78 dropped support for XPCOM-/XUL-APIs.
So... SignatureSwitch had to be completely rewritten.
Which means... we basically have a completely new add-on (structure).

> It does not recognise any previous signature files, even though they are still in the C:\Users*********\AppData\Roaming\Thunderbird\Profiles*********.default\Signatures directory.

As explained above.
New add-on code.
Data from the old version doesn't automatically get migrated / brought over.

> So, I chose SW button>Signatures>New Signature I can change the name, but I can't edit the default text (plain or html). The "Moe Zilla" text is not selectable. The cursor sits in the upper left corner of the edit window. Suggestions? Thanks.

The input-fields are standard HTML elements.
So I assume something else is broken in your Thunderbird installation.

> --------- UPDATE ---------
> I changed the name of the signature and saved it. Opened a new message, Inserted the signature, which was empty. From the message window I selected SW button>Options and then I was able to edit the signature. In other words, it fixed itself. But there is a bug in there somewhere. Hope that helps.

Can't reproduce your issues.
