### ISSUE TITLE
Problems with auto switch on reply and forward

### ISSUE THREAD

**Issue by Freddyvdh** [4ch1m/mozext#14]
Hi,

first of all a big thanks for migrating to TB 78 support 👍

I have a problem with the auto switch on a reply. I want to disable the footer on company internal mails, so I created a blank signatuere with Auto switch '*@company.de'. It works on new messages fine.

On a reply the signature is only removed, when the address is removed and added again.
On a forward the address has to be removed and added again, but then the senders signature and not mine is removed.

I have multiple accounts, so that the signatures are set in the accounts - is that a problem?
If so, would it be a feature request to have the account(s) or the sender address in the signatures configuration?

Thanks
Freddy

**Comment by 4ch1m** [comment]
I'm already working on an "identity aware" configuration section. (Meaning: Different default-sigs for different accounts.)
Please check back later.

**Comment by 4ch1m** [comment]
A beta-version of the new version with auto-switch based on identities is available here:
http://mozext.achimonline.de/devbuilds.php
Would be cool if you could help testing.
Thanks.
