### ISSUE TITLE
Quoted text in plain-text messages is converted to regular text when adding signature

### ISSUE THREAD

**Issue by hb9tst** [4ch1m/mozext#15]
Hi, thanks for bringing this extension to TB 78 in a short time, great work!

On Thunderbird, I have the plain-text editor set as default, and have no default signature set. When answering messages, if I add a signature using Signature Switch, the quoted text in the message is converted to regular plain text (including the '> ' characters of the quotation), which means that the mail will be sent by Thundebird with spaces in front of the '> ' to make sure they _wont_ be considered quotes by the recipient MUA.

As an example, here is a mail before adding a signature. The quoted text is clearly visible in blue, while the answer is in white:
![image](https://user-images.githubusercontent.com/30394208/97573107-8dae0b00-19e9-11eb-92f7-1f4b4b22fb1c.png)

Now, if I add a signature, the quoted text becomes regular text, and sometimes even jumps on the next line because of line wrapping, making the thins even messier:
![image](https://user-images.githubusercontent.com/30394208/97573319-d82f8780-19e9-11eb-8c4f-ef188ff7e930.png)

I'm not sure whether this is a bug/limitation of the MailExtension API of Thunderbird, or a bug in SignatureSwitch, but it is unfortunately very annoying... do you think it is possible to correct this or does Thunderbird needs a patch?

**Comment by 4ch1m** [comment]
That's a known problem.
(You'll find serveral bugzilla entries regarding this kind of issue.)

There's nothing you can do on MailExtension-/API-side.

However, you can manually trigger TB's native "rewrap" function; which should bring back the right colorization.

Also... you can tweak a few specific TB-preferences (like "mail.wrap_long_lines", e.g.) to work around the "jumps on the next  line" problem.

**Comment by jan-kiszka** [comment]
This is a critical issue, rendering the plugin useless for me as it destroys the layout of the cited text, even more then trying to rewrap. Back to manual mode...

Can you point to some concrete bugzilla entries that need to be solved in order to fix this? Would try to vote for it.

Is there anything that could be done by using an own API extension meanwhile?

**Comment by 4ch1m** [comment]
> This is a critical issue, rendering the plugin useless for me as it destroys the layout of the cited text, even more then trying to rewrap.

I can't see why this is "critical".
I also find this annoying to be honest.
But critical?

Just hit "Ctrl+r" and everything should be as expected.

> Back to manual mode...

Fine with me. :+1: 

> Can you point to some concrete bugzilla entries that need to be solved in order to fix this? Would try to vote for it.

Nope... you'll have to google it for yourself.
(I remember having read a couple of bugs regarding this issue; but haven't kept references to them.)

> Is there anything that could be done by using an own API extension meanwhile?

This is what the MailExtension-API offers: [ComposeDetails](https://thunderbird-webextensions.readthedocs.io/en/78/compose.html#composedetails)

And that's what I'm using.
Any colorization will be lost when setting the text via the `body`-attribute there.

Maybe it would be possible to create an [experiment](https://thunderbird-webextensions.readthedocs.io/en/78/how-to/experiments.html) to trigger Thunderbird's plaintext-colorization afterwards.
But I won't implement something like that, because I want Signature Switch to remain a pure MailExtension add-on.

**Comment by jan-kiszka** [comment]
This is what you get when not rewrapping, just applying the signature:
```
On 30.10.20 09:25, Jan Kiszka wrote:
> From: Jan Kiszka <jan.kiszka@siemens.com>
>
> We won't disable it again because num_smmu_devices will not be
> incremented on error.
>
> Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>
> ---
>  hypervisor/arch/arm64/smmu.c | 9 +++++----
>  1 file changed, 5 insertions(+), 4 deletions(-)
>
> diff --git a/hypervisor/arch/arm64/smmu.c b/hypervisor/arch/arm64/smmu.c
> index 89631d16..2e616204 100644
> --- a/hypervisor/arch/arm64/smmu.c
> +++ b/hypervisor/arch/arm64/smmu.c
> @@ -238,7 +238,7 @@ static int arm_smmu_device_reset(struct
arm_smmu_device *smmu)
>  	void *gr0_base = ARM_SMMU_GR0(smmu);
>  	unsigned int idx;
>  	u32 reg;
> -	int ret;
> +	int err;
>
>  	/* Clear global FSR */
>  	reg = mmio_read32(ARM_SMMU_GR0(smmu) + ARM_SMMU_GR0_sGFSR);
> @@ -295,10 +295,11 @@ static int arm_smmu_device_reset(struct
arm_smmu_device *smmu)
>  	reg |= sCR0_VMIDPNE | sCR0_PTM | sCR0_USFCFG;
>
>  	/* Push the button */
> -	ret = arm_smmu_tlb_sync_global(smmu);
> -	mmio_write32(ARM_SMMU_GR0(smmu) + ARM_SMMU_GR0_sCR0, reg);
> +	err = arm_smmu_tlb_sync_global(smmu);
> +	if (!err)
> +		mmio_write32(ARM_SMMU_GR0(smmu) + ARM_SMMU_GR0_sCR0, reg);
>
> -	return ret;
> +	return err;
>  }
>
>  static int arm_smmu_device_cfg_probe(struct arm_smmu_device *smmu)
>
```

And this is with rewrapping:
```
On 30.10.20 09:25, Jan Kiszka wrote:
> From: Jan Kiszka <jan.kiszka@siemens.com>
>
> We won't disable it again because num_smmu_devices will not be 
> incremented on error.
>
> Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com> --- 
> hypervisor/arch/arm64/smmu.c | 9 +++++---- 1 file changed, 5
> insertions(+), 4 deletions(-)
>
> diff --git a/hypervisor/arch/arm64/smmu.c
> b/hypervisor/arch/arm64/smmu.c index 89631d16..2e616204 100644 ---
> a/hypervisor/arch/arm64/smmu.c +++ b/hypervisor/arch/arm64/smmu.c @@
> -238,7 +238,7 @@ static int arm_smmu_device_reset(struct
arm_smmu_device *smmu)
> void *gr0_base = ARM_SMMU_GR0(smmu); unsigned int idx; u32 reg; -	int
> ret; +	int err;
>
> /* Clear global FSR */ reg = mmio_read32(ARM_SMMU_GR0(smmu) +
> ARM_SMMU_GR0_sGFSR); @@ -295,10 +295,11 @@ static int
> arm_smmu_device_reset(struct
arm_smmu_device *smmu)
> reg |= sCR0_VMIDPNE | sCR0_PTM | sCR0_USFCFG;
>
> /* Push the button */ -	ret = arm_smmu_tlb_sync_global(smmu); -
> mmio_write32(ARM_SMMU_GR0(smmu) + ARM_SMMU_GR0_sCR0, reg); +	err =
> arm_smmu_tlb_sync_global(smmu); +	if (!err) +
> mmio_write32(ARM_SMMU_GR0(smmu) + ARM_SMMU_GR0_sCR0, reg);
>
> -	return ret; +	return err; }
>
> static int arm_smmu_device_cfg_probe(struct arm_smmu_device *smmu)
>
```

In theory, I could disable line wrapping to avoid the first mess. But that wasn't needed so far and would require manual wrapping of my reply text.

The issue is not the colorization, that is probably just a symptom. It looks to me like TB is loosing track what is a citation and therefore drops the colors and starts line wrapping.

**Comment by 4ch1m** [comment]
Okay.
But I can't help you with that. Sorry.
As explained above... I'm using what is available.

This issue has nothing to do with Signature Switch or my code.

**Comment by jan-kiszka** [comment]
Already tried to work against the regular body, even in plaintext mode? That one seems to contain the magic information that gets lost when overwriting plainTextBody.

**Comment by 4ch1m** [comment]
Look... I really try to be helpful.
But as I tried to explain above. There's nothing I can do at this point.

This is where Signature Switch alters/replaces the composer-body ([background.js](https://github.com/4ch1m/mozext/blob/master/signatureswitch-me/src/background/background.js)):
```
async function appendSignatureToComposer(signature, tabId = composeActionTabId) {
...
    if (details.isPlainText) {
        cleansedBody += await createPlainTextSignature(signature.text);
        browser.compose.setComposeDetails(tabId, {plainTextBody: cleansedBody});
    } else {
...
        browser.compose.setComposeDetails(tabId, {body: xmlSerializer.serializeToString(document)});
    }
}
```
You're free to check out this code and try to improve things here.
I'm open for any pull-requests.

But if you're unhappy with the (MailExtension-)API, please open a Bugzilla ticket or talk to the maintainers the Thunderbird-codebase.

Thank you.

**Comment by jan-kiszka** [comment]
Read further, now in the TB code - understood now.

FWIW, I've opened https://bugzilla.mozilla.org/show_bug.cgi?id=1674830 as there was no directly related issue shown in the database.

**Comment by jan-kiszka** [comment]
OK, last reply, only a PR may follow: It seems like a composeScripts (https://thunderbird-webextensions.readthedocs.io/en/latest/composeScripts.html#) could do the trick, API-extension free. At least when simulating a modification via the inspector, editing the dom elements under `div class="moz-signature">`, this was propagated correctly.

If all signatures carry that div class, it may even make signature detection easier.

**Comment by jan-kiszka** [comment]
Time to reopen this issue: Still fresh, just hacked up this morning, testing. PR will follow soon if all is fine.

**Comment by 4ch1m** [comment]
Hi Jan,
looks promising.
How did your tests turn out?

**Comment by jan-kiszka** [comment]
Fairly well over the day. But it takes some more tuning of the space between text and signature. Something weird. Will follow up later.

**Comment by 4ch1m** [comment]
Gotcha. Thanks.
