### ISSUE TITLE
Relics from old versions in prefs.js

### ISSUE THREAD

**Issue by lorenzk1** [4ch1m/mozext#16]
TB 48.4
Signature Switch up to 2.3.0

Hello Achim,
I have been using signature switch over the years and updated TB step by step. Now after installing new Signature Switch add-on I did not get it to work nor to see any menu items for several weeks...
Checking prefs.js showed many relics form older versions. After editing prefs.js, deleting all signature switch entries and reinstall of the extension everything is working fine!
So this must somehow be considered in the installation process.
Thank you very much for your efforts in creating important extensions
Karlheinz

**Comment by 4ch1m** [comment]
Hi Karlheinz,
thanks for your report.
Unfortunately there's not much I can do an that front.
The "new" SignatureSwitch still has the same add-on ID as the "old" SignatureSwitch.
But that's pretty much all.
The new codebase is completely different; it's a mail-extension now.
Meaning it doesn't "reuse" **anything** (configurations, etc.) from a previous installation.
So... if upgrading the add-on caused problems in your case, you might want to report that to the maintainers of Thunderbird.
Thanks.
