### ISSUE TITLE
Unable to install according to the instructions given!

### ISSUE THREAD

**Issue by virsto** [4ch1m/mozext#17]
:\Users\Virgil Stokes\mozext\signatureswitch-me>npm install

> signatureswitch@ postinstall C:\Users\Virgil Stokes\mozext\signatureswitch-me
> ./copy_node_modules.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! signatureswitch@ postinstall: `./copy_node_modules.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the signatureswitch@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Virgil Stokes\AppData\Roaming\npm-cache\_logs\2020-11-08T18_30_36_223Z-debug.log
[2020-11-08T18_30_36_223Z-debug.log](https://github.com/4ch1m/mozext/files/5506968/2020-11-08T18_30_36_223Z-debug.log)

**Comment by 4ch1m** [comment]
no Windows support atm; sorry
