### ISSUE TITLE
Copy-Paste issues

### ISSUE THREAD

**Issue by gh658804** [4ch1m/mozext#19]
Apart from an initial Paste action to the HTML text (which worked fine), additional Copy or Paste actions in there do not work. I have tried Copying using either CTRL+C or context-menu Copy, but pasting to notepad pasted nothing.

Pasting to a new TB email however pasted this (1st image):

https://imgur.com/a/XABBwDa

Doubleclicking on it, displays the dialog that appears in the 2nd image.

**Comment by 4ch1m** [comment]
I'm afraid I can't follow you on that.
* "initial Paste action to the HTML text"???
* "pasting to notepad pasted nothing"???
* The images you reference show an "Advanced Property Editor". What does that have to do with Signature Switch???

Please be more specific/precise and explain all steps to reproduce.

Besides... telling me which versions (Thunderbird and Signature Switch) you're using would also help.

**Comment by FabianWehning** [comment]
I think I have the same (or similar) Problem.

I am able to paste into the signature form (plain text or html) but it is not possible to retrieve the information via copying it (neither [Ctrl] + [C] or via context menu). If you try to copy the text, the clipboard is empty. Same issue in the "Import/Export" section.

**Comment by gh658804** [comment]
Hey Achim,

TB 78.4.3, SS 2.3.0

Select and copy some text from a file and paste it to the editbox of Signature editor. This works fine.

Select and copy some text from the signature editor textbox to either another place of the signature editor textbox or a notepad. Nothing is pasted. It may seem like the clipboard is empty (like FabianWehning reported) but in fact the "copy" process has copied **the textbox object itself** in the clipboard and not its contents (The images you reference show an "Advanced Property Editor" - of course, this appears when i doubleclick on the object i've pasted in TB's editor, because TB's editor recognizes it and pastes it normally, unlike notepad which pastes nothing).

**Comment by 4ch1m** [comment]
OK. Gotcha.
I'll have a look into this.

**Comment by 4ch1m** [comment]
Confirmed.
I have no idea why that happens though.

**Comment by gh658804** [comment]
May be a TB bug?

**Comment by gh658804** [comment]
As a workaround and until this is fixed, is there a way to manually edit the signature settings? Are they stored in a text file or perhaps using the builtin TB config editor?

**Comment by 4ch1m** [comment]
OK... I spent quite some time to figure out that this actually **IS** a bug in Thunderbird! :sweat_smile: 
see: [options-test](https://github.com/4ch1m/sandbox/tree/master/options-test)

I've implemented a workaround (available in the next release); hoping this will be fixed soon in the codebase.
