### ISSUE TITLE
Signature always appended when forwarding

### ISSUE THREAD

**Issue by mforkel** [4ch1m/mozext#2]
When I forward a message, a signature is always appended. This does not happen if Signature Switch ist disabled. 

I'm using Signature Switch 1.8.2 in Thunderbird 68.11.0 on Windows 10. I have disabled both options to append signatures in Composition & Adressing section for all my email accounts,

**Comment by 4ch1m** [comment]
Development on the legacy-codebase (XUL/XPCOM) of SignatureSwitch (= versions below 2.0) is discontinued.
So there won't be any fixes for that. Sorry.
New codebase: [signatureswitch-me](https://github.com/4ch1m/mozext/tree/master/signatureswitch-me)
