### ISSUE TITLE
Signature Switch: missing signature file feature

### ISSUE THREAD

**Issue by mod20388** [4ch1m/mozext#23]
In the older versions of Signature Switch, it used to be so that I could setup a file for each signature. That is, updating the file automatically updated the signature used in Thunderbird. (This is highly practical since I could then synchronize my signatures using Nextcloud/Dropbox/whatever in a portable way.)

Unfortunately, this feature is missing from the newer versions (and the older ones are not compatible with Thunderbird 78.4+). The only way I see to add new signatures is to paste them into the config panel. Was there a reason for it to be dropped?

**Comment by 4ch1m** [comment]
> Was there a reason for it to be dropped?

Yes. Please read the [FAQ](http://mozext.achimonline.de/signatureswitch-me.php#faq) (item 6).
