### ISSUE TITLE
Signature Switch: widget problems (assign signature to identity)

### ISSUE THREAD

**Issue by Moilleadoir** [4ch1m/mozext#26]
This could well be something you can do nothing about, but I thought you should at least know in case you get support requests.

I’m using the Cinnamon desktop & Manjaro Linux, but I’d guess it’s probably the same in all GTK environments.

After installing the new version, I set up signatures, but could not assign a signature to an identity. The widgets did not respond at all. Before reporting it I decided to try again and after a lot of clicking & double-clicking I did eventually get  a response. I can now assign signatures, but it’s not a smooth process.

The widgets seem to only have a small area on the left that responds. The arrows are completely unresponsive. Maybe beyond your control, but worth knowing about.

When accessed using the keyboard (TAB + arrows) they work as expected, but it didn’t occur to me to try that!

![Signature Switch widgets](https://user-images.githubusercontent.com/1229543/100413563-ccf47800-30cb-11eb-86a8-9a0bbc4bd0d7.jpg)
*The widget only becomes active to the left of where the cursor is.*

**Comment by 4ch1m** [comment]
Hey @Moilleadoir ,
thanks for your report.
I can't reproduce this. Everything works fine both on my Linux workstation, and my Windows laptop.
Also haven't heard about anything like this... so far. :)
I'll close this for now, since I don't consider this an issue of my add-on.
