### ISSUE TITLE
View HTML tab automatically in signature edit

### ISSUE THREAD

**Issue by gh658804** [4ch1m/mozext#28]
In the signature edit window, i personally use HTML signatures only. It would be nice if there was an option (boolean) in order to show the HTML part automatically when you edit a signature, instead of the "text" which is now the default.

**Comment by 4ch1m** [comment]
Having specific options for display-preferences within the actual options-/preferences-dialog seems like overkill to me; also: you don't add/edit signatures every day. So I think this would add more complexity than really needed.
Sorry... closing.
