### ISSUE TITLE
Can't switch signature during email writing

### ISSUE THREAD

**Issue by Tomo59** [4ch1m/mozext#29]
Hello,

in the previous version, we could change signature after the email is written (there was a "Signature Switch" line in the option tab).

I have the case of 2 people using the same email address and only switching their signature to distinguish between them.

Is it still possible ?

Thnaks.

Thomas.

**Comment by 4ch1m** [comment]
Yes, of course it is.
Just click on the SignatureSwitch-button in the toolbar and select the signature you want - whenever you want.
(If you don't see the button in the toolbar => right click on the toolbar and customize it.)

**Comment by Tomo59** [comment]
Thank you very much. Indeed I didn't see we could add the button in the toolbar.
