### ISSUE TITLE
Add entry in "Addon options" instead of main window button

### ISSUE THREAD

**Issue by gh658804** [4ch1m/mozext#30]
I have noticed that in menu Tools, somehow a submenu "Addon options" appear when there are configurable addons. It would be better if Signature Switch could add an entry there instead of having the button in the main window (having it in the "Write" window is just fine though). Signature Switch's options are something that will be rarely used, so having a button in the main window is overkill IMO.

**Comment by 4ch1m** [comment]
You can always remove that button from the main-window, if you wish to.
Right-click... customize... drag it out of the toolbar. Done.
And... IMHO it is not "overkill" to have it there.
Closing; since this is not an issue at all.
