### ISSUE TITLE
HTML code question (or issue)

### ISSUE THREAD

**Issue by Thefaroah** [4ch1m/mozext#37]
Below code only gives me a black border. Border, width and height work as expected.

`<img src="{{Logo}}" border="3" bordercolorlight="#006fdd" bordercolordark="#b9dcff" width="70" height="80">`

New at HTML, and trying to explore things. Any helpful documentation?

**Comment by 4ch1m** [comment]
If you added an image with the exact same tag, then this should work.
Other than that I can't provide additional support based on your input.
This also isn't the right place for HTML-tutorials. Sorry.
Closing; since this is not really an issue.
