### ISSUE TITLE
There is requiring confirmation and then there is . . this

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [4ch1m/mozext#38]
![image](https://user-images.githubusercontent.com/47056543/110486375-7f34d600-80e4-11eb-9dff-94e3e06c1251.png)

- That is a _third_ confirmation window.
- It is not obvious how one uses the confirmation window. For, am I to type a dash at any point?
- The solicited arrow keys get passed to the window underneath as well as to the confirmation window itself: pressing those keys moves one around in another window.

You would do much better to copy the Linux utility `apt`, which, in the case of some operations, requires the following for confirmation: first, typing `y`/`yes`; second, typing (something like) `do as I say`. So: two confirmations, not three; and no - somewhat malfunctioning - arrow keys and dashes.

Thank you for your addOn.

**Comment by 4ch1m** [comment]
> That is a third confirmation window.

Yes. Right. That is correct.

> It is not obvious how one uses the confirmation window. For, am I to type a dash at any point?

No. That's why it isn't rendered as a key.

> The solicited arrow keys get passed to the window underneath as well as to the confirmation window itself: pressing those keys moves one around in another window.

So... what exactly is the *problem* here?

> You would do much better to copy the Linux utility apt, which, in the case of some operations, requires the following for confirmation: first, typing y/yes; second, typing (something like) do as I say. So: two confirmations, not three; and no - somewhat malfunctioning - arrow keys and dashes.

Well... I respect your opinion/preference. But... no. Won't implement.

This confirmation-dialog was meant to be funny (hint: "Konami code").
Obviously it isn't funny for everyone. Guess I failed. :smile: 

Closing, since this is not an "issue".
