### ISSUE TITLE
Adding more recipients to an email wipes out the email body

### ISSUE THREAD

**Issue by remyjacob** [4ch1m/mozext#42]
To reproduce the issue (Im using latest Thunderbird version on Windows):

1. Create a brand new email 
2. Start typing some text in the mail body (before the signature)
3. Change the email recipients list
4. The email body is removed

This is very annoying as you have to rewrite the entire email body.
Are you providing (will you provide) a setting to change this behavior ?

**Comment by 4ch1m** [comment]
You're probably composing your actual mail-text _inside_ the signature-block (presumably the first line of the signature)... basically "enhancing" the signature at the beginning.
That's why it may be gone when the signature gets switched.
What does the paragraph-dropdown show when you start composing? -> "Paragraph"? "Body Text"? "Preformat"?

![image](https://user-images.githubusercontent.com/3408832/112349044-aedd0400-8cc8-11eb-8cf5-e618c14b1098.png)

**Comment by 4ch1m** [comment]
Just hit enter before you start composing your text; making sure you start in a paragraph (not inside the signature).

**Comment by remyjacob** [comment]
That's what I already do !

**Comment by remyjacob** [comment]
Why are you so agressive ?
I love your extension, thank you for developing it !  but you've closed my issue twice and do not provide a real solution.
I just try to answer your questions the best I can so you can improve SignatureSwitch 

I'm using SignatureSwitch for the signature.
When I create a new mail, the signature is automatically inserted in the email body (fine !), I hit return before the signature and start typing few words. Then I start typing some email address in the 'To' field and my few words are wipped out. 

Here's my signature HTM code :
<table style="font-size: medium; font-family: Arial;" class="sc-gPEVay eQYmiW" cellspacing="0" cellpadding="0">
    <tbody>
        <tr>
            <td>
                <table style="font-size: medium; font-family: Arial;" class="sc-gPEVay eQYmiW" cellspacing="0"
                    cellpadding="0">
                    <tbody>
                        <tr>
                            <td style="vertical-align: top;">
                                <table style="font-size: medium; font-family: Arial;" class="sc-gPEVay eQYmiW"
                                    cellspacing="0" cellpadding="0">
                                    <tbody>
                                        <tr>
                                            <td style="text-align: center;" class="sc-TOsTZ kjYrri"><img
                                                    src="https://zejacobfamily.fr/remyjacob.jpg" role="presentation"
                                                    style="max-width: 128px; display: block;" class="sc-cHGsZl bHiaRe"
                                                    width="130"></td>
                                        </tr>
                                        <tr>
                                            <td height="30"></td>
                                        </tr>
                                        <tr>
                                            <td style="text-align: center;" class="sc-TOsTZ kjYrri"><img
                                                    src="https://zejacobfamily.fr/upec.jpg" role="presentation"
                                                    style="max-width: 130px; display: block;" class="sc-cHGsZl bHiaRe"
                                                    width="130"></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                            <td width="46">
                                <div></div>
                            </td>
                            <td style="padding: 0px; vertical-align: middle;">
                                <h3 color="#000000" style="margin: 0px; font-size: 18px; color: rgb(0, 0, 0);"
                                    class="sc-fBuWsC eeihxG"><span>Rémy</span><span>&nbsp;</span><span>JACOB</span></h3>
                                <p color="#000000" font-size="medium"
                                    style="margin: 0px; color: rgb(0, 0, 0); font-size: 14px; line-height: 22px;"
                                    class="sc-fMiknA bxZCMx"><span>Responsable domaines formation, documentation et
                                        pédagogie</span></p>
                                <p color="#000000" font-size="medium"
                                    style="margin: 0px; font-weight: 500; color: rgb(0, 0, 0); font-size: 14px; line-height: 22px;"
                                    class="sc-dVhcbM fghLuF"><span>DIRECTION DES SYSTEMES
                                        D'INFORMATION</span><span>&nbsp;|&nbsp;</span><span>Université Paris-Est Créteil
                                        Val de Marne</span></p>
                                <table style="font-size: medium; font-family: Arial; width: 100%;"
                                    class="sc-gPEVay eQYmiW" cellspacing="0" cellpadding="0">
                                    <tbody>
                                        <tr>
                                            <td height="30"></td>
                                        </tr>
                                        <tr>
                                            <td color="#F2547D" direction="horizontal"
                                                style="width: 100%; border-bottom: 1px solid rgb(242, 84, 125); border-left: medium none; display: block;"
                                                class="sc-jhAzac hmXDXQ" height="1"></td>
                                        </tr>
                                        <tr>
                                            <td height="30"></td>
                                        </tr>
                                    </tbody>
                                </table>
                                <table style="font-size: medium; font-family: Arial;" class="sc-gPEVay eQYmiW"
                                    cellspacing="0" cellpadding="0">
                                    <tbody>
                                        <tr style="vertical-align: middle;" height="25">
                                            <td style="vertical-align: middle;" width="30">
                                                <table style="font-size: medium; font-family: Arial;"
                                                    class="sc-gPEVay eQYmiW" cellspacing="0" cellpadding="0">
                                                    <tbody>
                                                        <tr>
                                                            <td style="vertical-align: bottom;"><span color="#F2547D"
                                                                    width="11"
                                                                    style="display: block; background-color: rgb(242, 84, 125);"
                                                                    class="sc-jlyJG bbyJzT"><img
                                                                        src="https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/phone-icon-2x.png"
                                                                        color="#F2547D"
                                                                        style="display: block; background-color: rgb(242, 84, 125);"
                                                                        class="sc-iRbamj blSEcj" width="13"></span></td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                            <td style="padding: 0px; color: rgb(0, 0, 0);"><a
                                                    href="tel:+33 (0)1 45 17 71 43" color="#000000"
                                                    style="text-decoration: none; color: rgb(0, 0, 0); font-size: 12px;"
                                                    class="sc-gipzik iyhjGb"><span>+33 (0)1 45 17 71 43</span></a></td>
                                        </tr>
                                        <tr style="vertical-align: middle;" height="25">
                                            <td style="vertical-align: middle;" width="30">
                                                <table style="font-size: medium; font-family: Arial;"
                                                    class="sc-gPEVay eQYmiW" cellspacing="0" cellpadding="0">
                                                    <tbody>
                                                        <tr>
                                                            <td style="vertical-align: bottom;"><span color="#F2547D"
                                                                    width="11"
                                                                    style="display: block; background-color: rgb(242, 84, 125);"
                                                                    class="sc-jlyJG bbyJzT"><img
                                                                        src="https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/email-icon-2x.png"
                                                                        color="#F2547D"
                                                                        style="display: block; background-color: rgb(242, 84, 125);"
                                                                        class="sc-iRbamj blSEcj" width="13"></span></td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                            <td style="padding: 0px;"><a href="mailto:remy.jacob@u-pec.fr"
                                                    color="#000000"
                                                    style="text-decoration: none; color: rgb(0, 0, 0); font-size: 12px;"
                                                    class="sc-gipzik iyhjGb"><span>remy.jacob@u-pec.fr</span></a></td>
                                        </tr>
                                        <tr style="vertical-align: middle;" height="25">
                                            <td style="vertical-align: middle;" width="30">
                                                <table style="font-size: medium; font-family: Arial;"
                                                    class="sc-gPEVay eQYmiW" cellspacing="0" cellpadding="0">
                                                    <tbody>
                                                        <tr>
                                                            <td style="vertical-align: bottom;"><span color="#F2547D"
                                                                    width="11"
                                                                    style="display: block; background-color: rgb(242, 84, 125);"
                                                                    class="sc-jlyJG bbyJzT"><img
                                                                        src="https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/link-icon-2x.png"
                                                                        color="#F2547D"
                                                                        style="display: block; background-color: rgb(242, 84, 125);"
                                                                        class="sc-iRbamj blSEcj" width="13"></span></td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                            <td style="padding: 0px;"><a href="//www.u-pec.fr" color="#000000"
                                                    style="text-decoration: none; color: rgb(0, 0, 0); font-size: 12px;"
                                                    class="sc-gipzik iyhjGb"><span>www.u-pec.fr</span></a></td>
                                        </tr>
                                        <tr style="vertical-align: middle;" height="25">
                                            <td style="vertical-align: middle;" width="30">
                                                <table style="font-size: medium; font-family: Arial;"
                                                    class="sc-gPEVay eQYmiW" cellspacing="0" cellpadding="0">
                                                    <tbody>
                                                        <tr>
                                                            <td style="vertical-align: bottom;"><span color="#F2547D"
                                                                    width="11"
                                                                    style="display: block; background-color: rgb(242, 84, 125);"
                                                                    class="sc-jlyJG bbyJzT"><img
                                                                        src="https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/address-icon-2x.png"
                                                                        color="#F2547D"
                                                                        style="display: block; background-color: rgb(242, 84, 125);"
                                                                        class="sc-iRbamj blSEcj" width="13"></span></td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                            <td style="padding: 0px;"><span color="#000000"
                                                    style="font-size: 12px; color: rgb(0, 0, 0);"
                                                    class="sc-csuQGl CQhxV"><span>61, Avenue du Général de Gaulle, 94
                                                        010 CRETEIL CEDEX France</span></span></td>
                                        </tr>
                                    </tbody>
                                </table>
                                <table style="font-size: medium; font-family: Arial;" class="sc-gPEVay eQYmiW"
                                    cellspacing="0" cellpadding="0">
                                    <tbody>
                                        <tr>
                                            <td height="30"></td>
                                        </tr>
                                    </tbody>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>

**Comment by 4ch1m** [comment]
> Why are you so agressive ?

Excuse me?! I'm in no way agressive here.
I wasn't the one giving one-line responses ending with an exclamation mark. :smile: 

> I love your extension, thank you for developing it ! but you've closed my issue twice and do not provide a real solution.

I've closed it *once* (and haven't re-opened it since)... simply because I was under the assumption that this is obviously a faulty configuration on your end; not an "issue/bug".

> I just try to answer your questions the best I can so you can improve SignatureSwitch

Much appreciated.
But how do you expect me to help with little to no information about all of your settings/configuration.

> I'm using SignatureSwitch for the signature.
> When I create a new mail, the signature is automatically inserted in the email body (fine !), I hit return before the signature and > start typing few words. Then I start typing some email address in the 'To' field and my few words are wipped out.

What happens to the "paragraph format"-dropdown after you hit return and insert a new line at the top?
Does it still show "Body text", or "Paragraph"?

If it still shows "Body text"... please try to make the first/empty line a paragraph.
Then try again if everything still disappers when typing in recipients.
