### ISSUE TITLE
mail.identity.default.supress_signature_separator not working

### ISSUE THREAD

**Issue by bvj1972** [4ch1m/mozext#44]
Hello,

the signature switch is working great. However, I want to remove the two dashes that appears above my html signature. I did the adjustment in the configuration editor (https://support.mozilla.org/en-US/questions/1019583), but the dashes still appears. I have another Thunderbird installation without Signature Switch, and in there I can remove the two dashes using config editor in Thunderbird.
![supress_signature_separator](https://user-images.githubusercontent.com/50927521/124374612-0104cc80-dc9d-11eb-8ba9-a84c35e9da1f.png)

**Comment by 4ch1m** [comment]
Hi there,
(as of now) MailExtensions don't have access to Thunderbird's native config/preference system.
So... SignatureSwitch can't read this setting and take it into consideration.
Besides: The signature separator is a crucial part of a plain-text message; it is needed to separate the actual mail-body from the signature when removing/switching signatures.
Please also check RFC 3676.
Thanks.
