### ISSUE TITLE
Signature Switch shortens horizontal lines (underscores)

### ISSUE THREAD

**Issue by astroneer** [4ch1m/mozext#47]
Thunderbird 91.0
Signature Switch 2.8.0
I think this issue came up with the last update to 2.8.0 (it did not happen before 02.09.2021):

- Normal text signatures (not html)
- Signatures include a lot of underscores to create a horizontal line
- When signature is inserted the horizontal line is reduced to 2 underscores

"______________________________________________________________________"
->
"__"

I first thought that there could be a kind of auto option to replace such a kind of text, but I couldn't find anything.
Perhaps something was introduced in 2.8.0 ?

**Comment by 4ch1m** [comment]
Nice catch, @astroneer. :+1: 

This was a bug; will be fixed with 64156b0.
Thanks for reporting.

**Comment by astroneer** [comment]
Thanks for your work and this great plugin :-)
