### ISSUE TITLE
Auto Switch domain list

### ISSUE THREAD

**Issue by rucksman** [4ch1m/mozext#48]
Is there a setting where I can use a domain list the other way round? As this should be a very common scenario, I am quite sure that it is possible, but I did not find the setting (I use this plugin and it's predecessor since many years). The scenario is: insert a signature always but NOT when the domain is a specific domain like the company domain (i.e. do not insert a signature for internal emails).

**Comment by 4ch1m** [comment]
Simply create an **empty** signature and set the "Auto Switch" domains as needed. Should fit your use-case.
