### ISSUE TITLE
Icon unreadable on light theme

### ISSUE THREAD

**Issue by crystalfp** [4ch1m/mozext#5]
Could the icon be more dark? With a light theme is invisible.

![image](https://user-images.githubusercontent.com/865866/95330747-4bd9eb00-08a9-11eb-9952-2d7cec344084.png)

Thanks!
mario

**Comment by 4ch1m** [comment]
That is strange.
The icon actually is black for the default (light) theme:
![](http://mozext.achimonline.de/img/signatureswitch-me/signatureswitch-me_screenshot1.png)

There's even special handling of icons for light/dark themes defined in the [manifest](https://github.com/4ch1m/mozext/blob/master/signatureswitch-me/src/manifest.json):

```
"theme_icons": [
    {
      "dark": "/_images/signatureswitch-64px-white.png",
      "light": "/_images/signatureswitch-64px-black.png",
      "size": 64
    },
    {
      "dark": "/_images/signatureswitch-32px-white.png",
      "light": "/_images/signatureswitch-32px-black.png",
      "size": 32
    },
    {
      "dark": "/_images/signatureswitch-16px-white.png",
      "light": "/_images/signatureswitch-16px-black.png",
      "size": 16
    }
  ]
```

I'll need more info about your installation/settings to figure this out.

**Comment by crystalfp** [comment]
These are the theme loaded and the one selected:
![image](https://user-images.githubusercontent.com/865866/95343388-c2321980-08b8-11eb-97b6-37afec1111d7.png)
If I switch to the default theme, the icon reappears in black.
Seems like this "light" theme (from Mozilla) is somehow not recognized.
Thunderbird 78.3.2
Anyway, switching to default theme seems that does not change anything compared to the "light" one. I solve the problem this way. Thanks!
mario

**Comment by 4ch1m** [comment]
You... you may report this finding in the official Thunderbird bugtracker. Thanks.

**Comment by crystalfp** [comment]
Done. https://bugzilla.mozilla.org/show_bug.cgi?id=1670017

**Comment by crystalfp** [comment]
They returned the ball to you. Sorry.

**Comment by 4ch1m** [comment]
No worries.
I already replied and created another bug. ;-)
Thanks, @crystalfp !
