### ISSUE TITLE
Rework / reactivate handling of Gmail quotes

### ISSUE THREAD

**Issue by 4ch1m** [4ch1m/mozext#50]
(re)integrate PR #49 from @ValdikSS

**Comment by 4ch1m** [comment]
Hi,

It's not a matter of understanding.
It simply is a matter of consideration regarding the use-case and complexity of this code-change.

The current code is simple and to the point.
Plus it covers probably 99% of all existing cases:


```
        if (node.nodeType === Node.ELEMENT_NODE &&
            node.nodeName === "BLOCKQUOTE" &&
            node.hasAttribute("type") && node.getAttribute("type") === "cite") {
            if (depth > maxDepth) {
                node.remove();
            } else {
                processHtmlBlockquotes(node.childNodes, replyHeaderHandling, maxDepth, depth + 1);
            }
        }
```

Your changes introduce two additional else-blocks which significantly raise complexity.

The same block now looks like this:

```
    for (let node of nodes) {
        if (node.nodeType === Node.ELEMENT_NODE &&
            node.nodeName === "BLOCKQUOTE" &&
            (node.hasAttribute("type") && node.getAttribute("type") === "cite" || // regular quote
            node.hasAttribute("class") && node.getAttribute("class") === "gmail_quote")) // gmail web interface quote
        {
            if (depth > maxDepth) {
                node.remove();
            } else {
                processHtmlBlockquotes(node.childNodes, replyHeaderHandling, maxDepth, depth + 1);
            }
        }
        else if (node.nodeType === Node.ELEMENT_NODE &&
            node.nodeName === "DIV" &&
            node.hasAttribute("class") && node.getAttribute("class") === "gmail_quote") // gmail web interface pre-quote div
        {
            processHtmlBlockquotes(node.childNodes, replyHeaderHandling, maxDepth, depth);
        }
        else if (node.nodeType === Node.ELEMENT_NODE &&
            node.nodeName === "DIV") // generic div
        {
            processHtmlBlockquotes(node.childNodes, replyHeaderHandling, maxDepth, depth);
        }
```

Additionally, this will degrade overall performance since these else-blocks will be executed for pretty much every node that doesn't fit to the initial if-condition.
(I've checked executions/iterations of these code parts for several test-mails; seeing countless useless recursions.)

Especially the last "else if" will hit *every* generic DIV that may have nothing to do with quotes in the first place.

Last but not least...
I will have to maintain this code in the future.
So, I personally don't think it's worth to integrate all of this just for the sake of a GMail corner-case.


I really appreciate your efforts and involvement, but I really prefer to keep the code clean/simple here.

**Comment by ValdikSS** [comment]
>Plus it covers probably 99% of all existing cases

If it was covering 99% of the cases, this patch won't have been created.
It seems you're using plain text email representation, while I use HTML view. In HTML view, NestedQuote Remover fail to perform its task quite frequently, it annoyed me up to the point that I, not a developer with near-zero Javascript knowledge, had to understand the issue and fix it, because the extension just doesn't work most of the time in my configuration.
It may work in some cases, like with quote depth=1, but not quote depth=3 what I use. With my patch, it works in much more cases, but also not in 100%, not even in 99%.

>So, I personally don't think it's worth to integrate all of this just for the sake of a GMail corner-case.

This is not only for Gmail. This covers most HTML-composed emails, including at least gmail web and outlook standalone.

If you making the extension for yourself and not for others, it's understandable that you don't want to merge the code you don't understand for the issue you don't hit, however for me the extension doesn't do what is it intended for, and I'm using my locally patched version this whole time.

**Comment by 4ch1m** [comment]
> If it was covering 99% of the cases, this patch won't have been created. It seems you're using plain text email representation, while I use HTML view. In HTML view, NestedQuote Remover fail to perform its task quite frequently, it annoyed me up to the point that I, not a developer with near-zero Javascript knowledge, had to understand the issue and fix it, because the extension just doesn't work most of the time in my configuration. It may work in some cases, like with quote depth=1, but not quote depth=3 what I use. With my patch, it works in much more cases, but also not in 100%, not even in 99%.

The extension is around for more than 15 years by now.
You're the **first** person that brings up this issue.

I'm not saying that it already works fine with Gmail messages.

But your changes are simply too invasive in order to get rolled out for everyone.

> This is not only for Gmail. This covers most HTML-composed emails, including at least gmail web and outlook standalone.

Your code clearly addresses "gmail_quote" in class-names:

```
node.hasAttribute("class") && node.getAttribute("class") === "gmail_quote")) // gmail web interface quote
```

So much for "most HTML-composed emails".

> If you making the extension for yourself and not for others, it's understandable that you don't want to merge the code you don't understand for the issue you don't hit, however for me the extension doesn't do what is it intended for, and I'm using my locally patched version this whole time.

Look...
This is free and open-source software.
I provide it and my servics without charge.
There are many happy users out there.

The source-code is open/free exactly for people like you.
If you want to make your own customized version... go ahead! Great.

If the software doesn't fit your needs then I'm sorry for the time you've lost so far.
But then I'd suggest to move on and go look elsewhere.

Thanks.

**Comment by ValdikSS** [comment]
If I make my method configurable with a checkbox in settings, and your method would be used otherwise by default, does that sound reasonable to be merged?

**Comment by ValdikSS** [comment]
@4ch1m, is that an acceptable method to merge the code? Kindly waiting for your reply.
