### ISSUE TITLE
Feature request: Auto switch only when all recepients match with a domain

### ISSUE THREAD

**Issue by prometoys** [4ch1m/mozext#51]
Hi,

I use auto-switch to distinguish between company internal and external recipients. But when I send an email to an external recipient and have at least one of my colleagues in the To: field, it switches the signature. A option to say match-one or match-all would be nice. Does this make sense for you?

Best
 
P.S.: Great extension!

**Comment by X-Softer** [comment]
I agree. That would be a useful option.

**Comment by 4ch1m** [comment]
@prometoys: Good idea. :+1:

implemented with 9997da9

![image](https://user-images.githubusercontent.com/3408832/147819997-582a1968-b87b-4a8d-9075-c4629f7982fa.png)

Will be out with the next release.
