### ISSUE TITLE
Switching a signature deletes all existing text

### ISSUE THREAD

**Issue by gh658804** [4ch1m/mozext#52]
In a new email window, i have written an email and at the end, before sending it i changed the signature using the "signature switch" button. As soon as i clicked on the new signature from the menu, all text i had written disappeared.

This had happened in the past with an older version and i was able to Undo and restore my text. With the current version though, even this does not work. As soon as a new signature is selected, the existing text is lost.

**Comment by X-Softer** [comment]
I have the same problem.
The problem also happend when "Autoswitch" is enable and I change/add recipient(s) adress(es).

**Comment by gh658804** [comment]
Hi.

This was happening to me because in the account settings, i had chosen a signature file. Signatureswitch’s instructions say that TB should not be responsible for setting the signature. As soon as I removed the signature from account settings and let Signatureswitch do its work without any interference, it worked fine.

**Comment by 4ch1m** [comment]
This is most likely happening when the actual mail text gets composed "inside" the signature-block/-paragraph.

Signature Switch v2.9.0 now has a visual separator to clearly distinguish the mail body from the signature while composing. (The separator doesn't get sent with the actual mail or shown when printed.)
This should mitigate issues like this.
