### ISSUE TITLE
Editor for plaintext signature uses proportional font

### ISSUE THREAD

**Issue by fthommen** [4ch1m/mozext#55]
The editor for plaintext signatures uses a proportional font, which makes it almost impossible to design signatures with correctly aligned indentations

Signature Switch version: 2.9.0
Thunderbird version: 91.4.1
Operating system: mac OS Monterey 12.0.1

**Comment by 4ch1m** [comment]
And what exactly makes you think this is related to the Signature Switch Add-On in first place? :smile:

**Comment by 4ch1m** [comment]
Ah... sorry... you mean the editor in the options UI?

**Comment by 4ch1m** [comment]
Valid point. :+1: 
Implemented/improved with d72c25f.
Thanks for the suggestion.
