### ISSUE TITLE
Signature Switch's Fortune Cookie text file import munges accented characters in ANSI-Encoded text files.

### ISSUE THREAD

**Issue by gungfujoe** [4ch1m/mozext#58]
Sorry for the email AND issue report.  I didn't think of posting on Github until I sent my email. :)

I seem to have found a small bug in the text import routine. Back when FileZilla was working, I used a list of quotes as a random tagline below my signature.  One of them is credited to "Henri Poincaré" in the text file, but imported into Signature Switch as "Henri Poincar�" (a diamond with a question mark in it, but in the Ctrl-U source of the plain-text email I sent you, the character renders as "ï¿½").  I was able to replace the character with "é" in the Signature Switch configuration, so I assume it'll look correct next time it's randomly selected, but if I update my quote list and re-import it, it'll revert back to "�" unless I remember to fix it each time.

I'm using Signature Switch 2.10.0 on Thunderbird 91.6.1 (64-bit) in Windows 10. The quote list I'm trying to import is a plain old text file, last edited in Notepad++.

After digging deeper, **I realized that this text file probably has pedigree back to my old MS-DOS OLX taglines file. It's ANSI-encoded, whereas newly-created text files are UTF-8 encoded.  If I convert the file to UTF-8, it imports successfully.**  Since I imagine a lot of the people wanting to use the "Fortune Cookies" feature are old-school packetmail users who have old tagline files lying around, though, it'd be best if Signature Switch recognized truly-plaintext (ASCII/ANSI) files and converted them upon import.

**Comment by 4ch1m** [comment]
Hey @gungfujoe,

You already pretty much figured it out by yourself. :smile:

The code segments which handle the file import are here ...

https://github.com/4ch1m/mozext/blob/239ad9a8d9d7497bb432fbee3dbe254842ce0fc0/signatureswitch-me/src/options/page.js#L456-L459

... and here:

https://github.com/4ch1m/mozext/blob/239ad9a8d9d7497bb432fbee3dbe254842ce0fc0/signatureswitch-me/src/common.js#L92-L99

The [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsText)'s default encoding is UTF8; which makes sense and should cover 99% of all common use-cases.
We *could* create an extra option/text-field for this in the UI (where other encodings can freely be entered) and pass the value along to the FileReader. But I think that would add more confusion and open up potential misuse.

The conversion of specific file formats should be done outside of SignatureSwitch.

Anyway... thanks for your report!
