### ISSUE TITLE
Native messaging from URL

### ISSUE THREAD

**Issue by luison** [4ch1m/mozext#59]
I've seen a closed issue with a similar question for a local file: https://github.com/4ch1m/mozext/issues/34
I understand this has to be handled currently with a local .js file only. Wondering if this method would also work for an external URL? We were hoping to incorporate a dynamic promotional message on our signatures extracted from a php script. Either the whole signature or a part.
Possible at all or restrictions from TB would make that impossible?

**Comment by 4ch1m** [comment]
The only way to properly get external data (afaik) is through "Native Messaging"... as described here: https://github.com/4ch1m/mozext/tree/master/signatureswitch-me/native_messaging

> I understand this has to be handled currently with a local .js file only.

Not quite correct.
You can use **any** executable (e.g. a Python-, Perl-, Bash-script, etc.) on your local machine.

> Wondering if this method would also work for an external URL?

This executable can do whatever is needed; also fetch data from an URL and pass it back to Thunderbird/SignatureSwitch.

> We were hoping to incorporate a dynamic promotional message on our signatures extracted from a php script. Either the whole signature or a part. Possible at all or restrictions from TB would make that impossible?

Absolutely possible.
Just write your own script/program which delivers the dynamic signature.

**Comment by luison** [comment]
Thanks for prompt reply but what I meant is that call can only be made to a local script installed on each TB client, not calling an external URL directly.

**Comment by 4ch1m** [comment]
How and where exactly do you want to "call" the external URL?

**Comment by 0nelight** [comment]
I solved this per putting two functions into common.js which download the signatures.json and images.json from an IP within my LAN and overwrite the according browser.storage.local json entries. Additionally you have to update the Permissions in the manifest.json file:
```diff
--- a/src/manifest.json
+++ b/src/manifest.json
@@ -65,6 +59,8 @@
     "page": "/options/page.html"
   },
   "permissions": [
+    "*://xxx.xxx.xxx.xxx/*",
+    "webRequest",
     "compose",
     "storage",
     "unlimitedStorage",
```

here is what the function looks like for gathering the signatures.json:
```javascript
function fetchSignaturesfromWebserver() {
    let req = new Request( "http://xxx.xxx.xxx.xxx/signatures.json", {
        method: 'GET',
        headers: { 'Accept': 'application/json' },
        redirect: 'follow',
        referrer: 'client'
    });

    fetch(req).then(function(response) {
        // .json returns another promise
        return response.json();
    }).then(function(data) {
        if(Array.isArray(data)) {
            browser.storage.local.set({signatures: data}); // set storage for content-script
        }
    }).catch(error => { console.log(error); });
}

fetchSignaturesfromWebserver();
```
