### ISSUE TITLE
Automatically add signature separator

### ISSUE THREAD

**Issue by tvercaut** [4ch1m/mozext#7]
The new signature switch allows one to specify arbitrary text in the signature but as far as I understood it, it should be standard practice to use `--` as a signature separator. It would be nice for signature switch to allow including the separator by default rather than asking the user to include it in their own signature.

On a related note, for html signatures, I curently resort to `--<br>` but am not sure this is best practice.

**Comment by 4ch1m** [comment]
Agreed.
Added this as an option to the new release (2.1.0).
