### ISSUE TITLE
[New feature] List of allowed signatures per identity

### ISSUE THREAD

**Issue by benintech** [4ch1m/mozext#78]
As it is now, all defined signatures are available, whatever the identity used to write the message is.

It would be nice to be able to associate not only a default signature to each identity, like it is the case now, but also a list of allowed signatures for each identity. In other words, to restrict each identity to a subset of the defined signatures.

Let's say I have 2 identities (ID1 and ID2), and that I defined 3 signatures in your extension (SIG1, SIG2 and SIG3). I'd like that ID1 can only choose between SIG1 and SIG2, and that it can never select SIG3

**Comment by 4ch1m** [comment]
Thanks four your input.
I get the idea.

However, I think the target audience for this feature is pretty small.
I also think that implementing this would further complicate the UI and make things more complex in general.
I also believe that very little people will have more thant a dozen signatures in total.
Thus... grouping/hiding them based on mail-identity seems overkill to me.

Anyway, I'll leave this feature-request open for now.
Maybe other people will show interest for this.
