### ISSUE TITLE
If you insert a signature, there will be an extra line break.

### ISSUE THREAD

**Issue by rosolino** [4ch1m/mozext#8]
Thank you for the nice add-on.
I am using Windows 10 64bit + Thunderbird 78.3.2 + signature switch 2.1.0.

When I write a new email and insert a signature using the signature switch, a new line is inserted into the body of the email as shown in the attachment.
![draft-before-in](https://user-images.githubusercontent.com/6219165/95814903-84b90a80-0d56-11eb-9ba5-184e9d804d16.png)
![after-sig](https://user-images.githubusercontent.com/6219165/95814921-8da9dc00-0d56-11eb-858c-8c9f1114f0d1.png)

**Comment by rosolino** [comment]
Yes,
I gave it two stars in the sense that the current state of affairs is a hindrance to its use.
Is it a problem with my environment?

**Comment by 4ch1m** [comment]
OK. I see.
Just out of curiosity: And what exactly was your intention behind that?

Get my attention and "motivate" me to reproduce/fix this alleged issue?
Or just warn other users about this "hindering" add-on by giving a low rating?

Either way...
Thanks for your contribution!
Can't find/reproduce this "bug".
Closing.

**Comment by rosolino** [comment]
I'm sorry if you were uncomfortable with the two stars.
I just wanted to report it to the author because it wasn't available in my environment and I hope it will benefit others.

In any case, I've changed my rating because it seems to be a symptom of a condition that has not been seen by others.
I hope it will be available in my environment someday.
