### ISSUE TITLE
Suggestion for cosmetic improvement

### ISSUE THREAD

**Issue by DenB10** [4ch1m/mozext#85]
Hello,
For purely aesthetic purposes, it would be nice to implement a dark theme in Signature Switch.
What do you think about it?

**Comment by 4ch1m** [comment]
Hey,
I'm totally open for that (but don't have the time to implement it myself atm).
However, I'll gladly accept a (working) pull-request.

**Comment by DenB10** [comment]
I tried to work on the cascading style sheets (compose.css and page.css) using other add-ons as a model and my poor skills but all I managed to do was to change the text and background color of the options page.
I think I also have to modify the two other css files located in the _libraries folder but it's too difficult for me, I give up...

**Comment by 4ch1m** [comment]
I finally found the time to work on this.
Just pushed the feature to the dev-branch: https://github.com/4ch1m/mozext/commit/d17a8f5c1cacab2d4cc1fb7ec39a4a05be9ddade

So... "Dark mode" will be available with the next release. :smile:
