### ISSUE TITLE
About dark theme (not an issue)

### ISSUE THREAD

**Issue by DenB10** [4ch1m/mozext#89]
I just updated the French translation for Signature Switch 2.15, sorry for the delay...

I tested the new dark theme, it works very well. Thanks for implementing it.
Nevertheless, two remarks:
1. The dark theme is activated "manually" via an option and not automatically when you use (like me) the dark theme of Thunderbird.
2. It would be nice if the dark theme also worked on the popup.

**Comment by 4ch1m** [comment]
>     1. The dark theme is activated "manually" via an option and not automatically when you use (like me) the dark theme of Thunderbird.

I'm aware of that.
Unfortunately I don't see any (obvious) way to detect Thunderbird's theme-settings via (extension-)code.
If you have any concrete ideas/implementations for that, a PR would be greatly appreciated.

>     2. It would be nice if the dark theme also worked on the popup.

What do you mean by "on the popup"?
Dialog-windows/popups should also appear in a dark theme.

**Comment by DenB10** [comment]
> What do you mean by "on the popup"?
> Dialog-windows/popups should also appear in a dark theme.

Sorry, I misspoke. What I call "popup" is the context menu that appears when you click on the "Signature Switch" toolbar button in the compose window.
But I found a way to make the dark theme apply to this menu too: you just have to modify the files "compose/popup.html" and "compose/popup.js":

[compose.zip](https://github.com/4ch1m/mozext/files/10558984/compose.zip)

Note: the theme change is immediate on this menu but not on the options page (you have to refresh it); it would be nice if the refresh of the options tab was automatic too!

> Unfortunately I don't see any (obvious) way to detect Thunderbird's theme-settings via (extension-)code.
> If you have any concrete ideas/implementations for that, a PR would be greatly appreciated.

Starting from the previous version of Signature Switch (2.14.0), I tried to copy the content of the file "_libraries/mdb.dark-min.css" (that is present in the new version 2.15.0) under `@media (preferences-color-scheme: dark) {...}` into the file "options/page.css". It works but the headers of the inactive tabs of the options page have not the right font size nor the right color. Probably a small change to make in this css?

For the button menu of the compose window, it's easier, just add a "compose/popup.css" like this one:

```
@media (prefers-color-scheme: dark) {
  .m-2 {
    background-color: #35393b;
  }
  hr {
    color: #b4b7b8;
  }
}
```
With reference in the "popup.html" file obviously.

**Comment by DenB10** [comment]
I think I managed to make a version that takes into account the Thunderbird theme without any special action from the user in the extension options.
There is still the icon of the context menu in the compose window, which is impossible to change according to the theme: black on black in dark theme, it's not very nice, the solution would be a colored icon!

I send it here because I don't see how to do it in "pull request":
[signature_switch-2.15.0mod-tb.zip](https://github.com/4ch1m/mozext/files/10571421/signature_switch-2.15.0mod-tb.zip)

**Comment by 4ch1m** [comment]
> Sorry, I misspoke. What I call "popup" is the context menu that appears when you click on the "Signature Switch" toolbar button in the compose window.

Oh. You're right.
I totally missed that one.
I just fixed/added that to the [dev-branch](ff45a9e503c5e1a6dde28567239faaeb8ae594b2).

> But I found a way to make the dark theme apply to this menu too: you just have to modify the files "compose/popup.html" and "compose/popup.js":

The extension is using [Material Design Bootstrap](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiAxLOns_f8AhVgSfEDHWTMAAsQFnoECBQQAQ&url=https%3A%2F%2Fmdbootstrap.com%2F&usg=AOvVaw2WQz5cihQVhS0G7aXcXEgj) for the UI.

So all (CSS-)definitions should come from that framework; and not from manual overrides.

> Note: the theme change is immediate on this menu but not on the options page (you have to refresh it); it would be nice if the refresh of the options tab was automatic too!

Yes. The standard (white) background color is present for a millisecond (until everything is done loading).
That's not perfect... but not a major annoyance, I guess.

> ... Probably a small change to make in this css?
> 
> For the button menu of the compose window, it's easier, just add a "compose/popup.css" like this one:
> 
> ```
> @media (prefers-color-scheme: dark) {
>   .m-2 {
>     background-color: #35393b;
>   }
>   hr {
>     color: #b4b7b8;
>   }
> }
> ```

Like mentioned above.
I'd like to stick with the definitions provided by MDB.

But thanks for your efforts, @DenB10. :+1:

**Comment by DenB10** [comment]
@4ch1m 

> Like mentioned above.
> I'd like to stick with the definitions provided by MDB.

Let me answer even if this thread is closed. I think you didn't see my second message in which I send you a mod that is entirely based on unchanged MDB.
Take a look at it and do what you want with it, I won't impose anything on you ;)

[signature_switch-2.15.0mod-tb.zip](https://github.com/4ch1m/mozext/files/10571973/signature_switch-2.15.0mod-tb.zip)

**Comment by 4ch1m** [comment]
Dude... that's awesome! :+1: :smile:

I just integrated it on the [dev-branch](https://github.com/4ch1m/mozext/commit/401e1904b41564dd9dbff8aa21d7919646a75baf).

Please provide a pull-request next time... so I can quickly see the changes... and you can claim credit for it. :wink:

Thanks, @DenB10.

**Comment by DenB10** [comment]
> Please provide a pull-request next time... so I can quickly see the changes... and you can claim credit for it. 

I know, I tried to make a pull request but I didn't succeed, I'm not very good :smile:
As for the credit, I don't care, it's not my goal!
