### ISSUE TITLE
Can't toggle signatures off and repeating bug

### ISSUE THREAD

**Issue by teknowledgist** [4ch1m/mozext#9]
Starting a new issue [from comment here](https://github.com/4ch1m/mozext/issues/4#issuecomment-707738799).

It's definitely still there.  I'm using Thunderbird 78.3.2.  I have one signature ("standard") that is simply a fortune cookie, and I do all my email in plain text.

1. Start a new message
2. Signature Switch toolbar button -> see "Switch on", "Standard" and "options".
3. click "Switch on" -> see signature
4. Toolbar button now shows "Switch off" (and the other two)
5 click "Switch off" -> newlines in mail become two with signature still there and "Switch off" still in menu
6. click "Switch off" again -> same result 
7. at some point (possibly after deleting body of email) menu changes to "Switch on"

Try again, and the same effect, except it never goes to "Switch off", always staying with "Switch on", and unlike with "Switch off", a new signature line is added.  (Again, after deleting the body of the message and clicking "Switch on" again, it changed to "Switch off".)

Clicking "Standard" (my signature name) at any point, and an additional signature shows up below the others.

Very strange if nobody else is seeing it.

(BTW, is the "default" signature supposed to be added to new messages by default?  Cause it's not.)

Thanks!

**Comment by 4ch1m** [comment]
I can't reproduce this on my machine (Linux 64 bit, Thunderbird 78.3.2).
Need more details about your setup.
A few screenshots and more detailed info about your signature ("simply a fortune cookie"?!) would also help.
Thanks.

**Comment by 4ch1m** [comment]
All right. Thanks.
I'll try to test this on a Windows machine.

**Comment by 4ch1m** [comment]
I just fired up my Windows10 machine.
I can reproduce the issue.
Not sure why this happens only on Windows, yet.
I'm on it.

**Comment by 4ch1m** [comment]
So... it turns out that this is a bug in the MailExtension-API (on Windows-machines).

Documented everything here:
https://github.com/4ch1m/sandbox/tree/master/composer-api
And opened a Bugzilla-ticket here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1672407

Don't know when/if this one will get fixed.
Also not sure if I will try to find my own fix/workaround in the meantime.

**Comment by teknowledgist** [comment]
Heh.  Figures.  

It's not a major issue (for me) since I don't need to change the signature often.  Thanks for looking into it and alerting Mozilla of the problem, and thank you again for rewriting this add-on.  It really is my favorite addition to Thunderbird!

**Comment by 4ch1m** [comment]
@teknowledgist , I've implemented a fix/workaround.

You can find the beta-version here:
http://mozext.achimonline.de/devbuilds.php

Could you please try it out and let me know, if this works for you.

Thanks!

**Comment by oparoz** [comment]
Good job. Sig switching works now :)

**Comment by hpreusse** [comment]
Looks better to me. Many thanks!

**Comment by teknowledgist** [comment]
It is much better, thank you.  

I think it is quite usable now, but there is still some kind of bug.  If I repeatedly click the button for the signature I want to use (i.e. "Normal"), the button for "Switch On" and "Switch Off" are not consistent.  Sometimes it is one and sometimes the other, but it seems rather unpredictable.  I don't know that this "new" problem really needs fixing because it seems to only be cosmetic and may only occur when nutballs like myself to goofy things, but I thought you might want to know about it.  

I'll close this since the initially-reported usability problem appears to be fixed.
