### ISSUE TITLE
Waiver of "--"

### ISSUE THREAD

**Issue by mdes** [4ch1m/mozext#99]
Hello,
How can I tap the "-" symbol on an AZERTY keyboard?
![2023-09-01 11 40 35 (Signature_Switch_-_Mozilla_Thunderbird)](https://github.com/4ch1m/mozext/assets/6514419/f4aac5ed-975b-4cf4-b9aa-c5beef601ada)
As soon as "-" is tapped from the keyboard or from the numeric keypad, I have to reenter all the sign.
Regards,
Michel.

**Comment by 4ch1m** [comment]
You don't have to press the `-` key (it's just a visual separator). Only the letters/keys in grey boxes.

**Comment by mdes** [comment]
👍
